data :
  name: DCASE2022  #MVTec #MTD #VisA 
  # category: ToyTrain_DDAD_1234_scale  # 统一模型的话不需要
  image_size: 256
  batch_size: 16
  imput_channel : 1


model:
  checkpoint_dir: checkpoints/DCASE2022   #MTD  #MVTec  #VisA
  checkpoint_name: weights
  exp_name: default
  learning_rate: 2e-4
  weight_decay: 0.05 
  epochs: 2000
  load_chp : 825 # From this epoch checkpoint will be loaded. Every 250 epochs a checkpoint is saved. Try to load 750 or 1000 epochs for Visa and 1000-1500-2000 for MVTec.
  eta : 1 # Stochasticity parameter for denoising process.
  v : 7 # Control parameter for pixel-wise and feature-wise comparison. v * D_p + D_f
  w : 1 # Conditionig parameter. The higher the value, the more the model is conditioned on the target image. "Fine tuninig this parameter results in better performance".
  time_steps: 1000
  test_time_steps: 999   # Starting point for denoining trajectory.
  skip : 50   # Number of steps to skip for denoising trajectory.
  beta_start : 0.0001
  beta_end : 0.02 
  device: 'cuda' #<"cpu", "gpu", "tpu", "ipu">
  save_model_epoch: 1000
  num_workers : 4
  seed : 42
  resume: False
  finetune_epoch: 100
  visual: False

# filepath
train_dirs:
  - /data/DCASE/2022/bearing/train
  - /data/DCASE/2022/fan/train
  - /data/DCASE/2022/gearbox/train
  - /data/DCASE/2022/slider/train
  - /data/DCASE/2022/ToyCar/train
  - /data/DCASE/2022/ToyTrain/train
  - /data/DCASE/2022/valve/train
test_dirs:
  - /data/DCASE/2022/bearing/test
  - /data/DCASE/2022/fan/test
  - /data/DCASE/2022/gearbox/test
  - /data/DCASE/2022/slider/test
  - /data/DCASE/2022/ToyCar/test
  - /data/DCASE/2022/ToyTrain/test
  - /data/DCASE/2022/valve/test
